### ISSUE TITLE
skill_manager loads skills from pyc files without existing python files

### ISSUE THREAD

**Issue by matthiashh** [RVMI/skiros2#15]
I ran into a couple of warning in the fashion:
```
PluginLoader        warn: WARNING: Multiple plugins with name demo_piston_insertion found!
[<class 'skills_sandbox.coordinator_psa_demos.demo_piston_insertion'>, <class 'skills_sandbox.demos.piston_insertion_demo.demo_piston_insertion'>]
```
As you might remember you recently restructured this repo. So I could find the current `.py` and the corresponding `.pyc` file. But I could also still find the `.pyc` at the old location and apparently the skill_manager tried to load that one as well.

I am not sure what the best solution would be. Delete `pyc` files on a regular basis? Check if there are still corresponding python file?
But I guess the result of this behavior could be that only the first implementation found will be loaded, which would probably confuse non-expert users.

**Comment by matthias-mayr** [comment]
This looks like it's only an issue if skill python files are moved and the old .pyc files remain. Closing.
