### ISSUE TITLE
Pip installation of rdflib leads to crash

### ISSUE THREAD

**Issue by frovida** [RVMI/skiros2#29]
When installing rdflib using, e.g.: pip install --user rdflib (installing the following: isodate-0.6.0 pyparsing-2.4.7 rdflib-5.0.0 six-1.14.0) on ubuntu 18.04 leads to the following:

[ERROR] [1588781225.330220]: Error processing request: cannot import name parser
['Traceback (most recent call last):\n', ' File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 632, in _handle_request\n response = convert_return_to_response(self.handler(request), self.response_class)\n', ' File "/home/francesco/ros_ws/rvmi_ws/src/libs/skiros2/skiros2/skiros2_world_model/src/skiros2_world_model/ros/ontology_server.py", line 44, in _wo_query_cb\n for s in self._ontology.query(msg.query_string, context_id=msg.context):\n', ' File "/home/francesco/.local/lib/python2.7/site-packages/wrapt/decorators.py", line 502, in _synchronized_wrapper\n return wrapped(*args, **kwargs)\n', ' File "/home/francesco/ros_ws/rvmi_ws/src/libs/skiros2/skiros2/skiros2_world_model/src/skiros2_world_model/core/ontology_rdflib.py", line 138, in query\n return self.ontology(context_id).query(query)\n', ' File "/home/francesco/.local/lib/python2.7/site-packages/rdflib/graph.py", line 1127, in query\n result = plugin.get(result, query.Result)\n', ' File "/home/francesco/.local/lib/python2.7/site-packages/rdflib/plugin.py", line 107, in get\n return p.getClass()\n', ' File "/home/francesco/.local/lib/python2.7/site-packages/rdflib/plugin.py", line 69, in getClass\n module = import(self.module_path, globals(), locals(), [""])\n', ' File "/home/francesco/.local/lib/python2.7/site-packages/rdflib/plugins/sparql/init.py", line 33, in \n from . import parser\n', 'ImportError: cannot import name parser\n']

**Comment by matthias-mayr** [comment]
Recently `python3-rdflib` give us this issue:
```
/wm:   File "/usr/lib/python3/dist-packages/rdflib/graph.py", line 1084, in query                                                                                           
/wm:     result = plugin.get(result, query.Result)                                                                       
/wm:   File "/usr/lib/python3/dist-packages/rdflib/plugin.py", line 104, in get                                                                             
/wm:     return p.getClass()                     
/wm:   File "/usr/lib/python3/dist-packages/rdflib/plugin.py", line 66, in getClass                                
/wm:     module = __import__(self.module_path, globals(), locals(), [""])                                                                                                      
/wm:   File "/usr/lib/python3/dist-packages/rdflib/plugins/sparql/__init__.py", line 35, in <module>               
/wm:     from . import parser                                                                                                                                                  
/wm:   File "/usr/lib/python3/dist-packages/rdflib/plugins/sparql/parser.py", line 182, in <module>                                                                            
/wm:     Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()     
/wm:   File "/usr/lib/python3/dist-packages/rdflib/plugins/sparql/parserutils.py", line 113, in __init__
/wm:     self.name = name                                                                                                                                                      
/wm: AttributeError: can't set attribute  
```
Installing it via pip resolves this though.

**Comment by matthias-mayr** [comment]
This is not an issue for me anymore. In 20.04, version 4.2.2-5 is installed as system package. 

Please re-open in case it should pop up again.
